### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by AsakusaRinne** [SciSharp/LLamaSharp#287]
Hi all, thanks to the community effort, LLamaSharp has had much richer features than the beginning. Meanwhile, the distributions of backend package may be changed soon. Therefore I think it's time to publish v1.0.0 in the next several weeks. In this issue, we discuss the roadmap to v1.0.0 and list the TODO-items. Any ideas about it is welcome here.

Required ones:
- [x] Include libraries of different avx supports in backend packages. #316 
- [x] Update the documentations. #267 .
- [ ] Enhance the text-completion APIs #239 
- [x] Major BUG fix #273 #265 #260 #118
- [ ] Improve local document search support. #289 #305 

possible ones:
- [x] Add benchmark test for LLamaSharp. #237 
- [x] Support .NET 8 since it's going to come out.
- [ ] Add android backend.

**Comment by AsakusaRinne** [comment]
I'm quite hesitant that if we should refactor the executors to support high-level batch decoding APIs in v1.0.0 because there's really a big amount of works. It's very useful for developing a more efficient service, but may delay our release for some weeks.

**Comment by martindevans** [comment]
I wouldn't expect a batch-decoding executor any time soon, it's going to be a _lot_ of work to design the API to support all of the various features in an easy to use way. So yeah I'd agree we shouldn't wait for it.

**Comment by darcome** [comment]
I would add support for stop sequence in Kernel Memory and "query your documents" feature, otherwise I am afraid is almost an unusable feature, which is bad, because at least from a company perspective, querying your own documents is the most useful thing rather than asking general questiosn to an AI.
What do you guys think?

**Comment by AsakusaRinne** [comment]
> I would add support for stop sequence in Kernel Memory and "query your documents" feature, otherwise I am afraid is almost an unusable feature, which is bad, because at least from a company perspective, querying your own documents is the most useful thing rather than asking general questiosn to an AI. What do you guys think?

Makes sense to me. Would you like to work on it? If your time is limited, it's okay to open an issue to leave it to us. :)

**Comment by darcome** [comment]
> > I would add support for stop sequence in Kernel Memory and "query your documents" feature, otherwise I am afraid is almost an unusable feature, which is bad, because at least from a company perspective, querying your own documents is the most useful thing rather than asking general questiosn to an AI. What do you guys think?
> 
> Makes sense to me. Would you like to work on it? If your time is limited, it's okay to open an issue to leave it to us. :)

Added issue #289 .

Unfortunately I would not even know where to start :)

**Comment by Webslug** [comment]
Please add a clearer example project in future.  It's really difficult as a newbie to get Llamasharp to work at all.  I'm about to give up on it, I tried the discord but it was fruitless.

**Comment by AsakusaRinne** [comment]
Sure, we will. Could you please give some specific suggestions, such as a certain example that confused you?

**Comment by nuwandw** [comment]
android backend please. I got the android binaries for llamacpp, but doesnt work with unity android project...

**Comment by lmxin123** [comment]
I am a developer from China who hopes to support more large models in China, such as Yi-32B-200k, Qwen-72b chat, etc

**Comment by Xsanf** [comment]
Version 0.8.1 deployed normally under Unity via NuGet packages. Version 0.9.1 is deployed with errors. Errors occur when installing Semantic Kernel and Kernel Memory. If possible, test the deployment. Most likely the problem is not too significant and it is better to fix it sooner. So that it does not cause accumulating problems with errors.

**Comment by martindevans** [comment]
@Xsanf could you open an issue with the errors you're seeing? Unity isn't one of our test targets, but if there are small tweaks we can make to improve compatibility we can certainly do that!

**Comment by Xsanf** [comment]
Unfortunately I have no experience with NuGet. Used it for the first time in this project. I installed according to the instructions https://github.com/eublefar/LLAMASharpUnityDemo

You don't even need to run the example itself. The problem occurs when importing NuGet packages. The LLamaSharp.kernel-memory.0.9.1 package imports only one LLamaSharp.kernel-memory.nuspec file. As far as I understand, the libraries themselves are not installed. There are no error messages. The LLamaSharp.semantic-kernel.0.9.1 package installs completely, but produces over 200 compilation errors. As far as I can understand, they arise due to a conflict with existing standard packages or due to a mismatch in the compilation target. There is no point in citing the errors themselves. You will see them when you try to install the package.

I'm guessing there's probably some kind of configuration error with the NuGet package.

Versions 0.7.1 and 0.8.1 were installed without errors and the example worked fine. So the error appeared only in version 0.9.1.

**Comment by dcostea** [comment]
I'm wondering if there are plans to make llama.cpp compatible with multi-modal input (images) for use with models like llava.

**Comment by SignalRT** [comment]
@dcostea 

> I'm wondering if there are plans to make llama.cpp compatible with multi-modal input (images) for use with models like llava.

#609 includes llava support on InteractiveExectutor

**Comment by dcostea** [comment]
> @dcostea
> 
> > I'm wondering if there are plans to make llama.cpp compatible with multi-modal input (images) for use with models like llava.
> 
> #609 includes llava support on InteractiveExectutor

I just can't wait to see it in the next release!
